<a href="https://colab.research.google.com/github/mdanisw/bootcamp-training/blob/main/Copy_of_Intro_to_Basic_Dataframe_(pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import pandas as pd
import numpy as np

In [35]:
data = pd.Series([1,2,3,4,5])

In [36]:
print(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [37]:
series_dt = pd.Series([np.array([2,3,4,5])])
series_dt

0    [2, 3, 4, 5]
dtype: object

In [38]:
data[2]

3

Creating DataFrame

In [39]:
data = pd.Series(["sabtu","siang","6-8-2022"],index=["a","b","c"])
data

a       sabtu
b       siang
c    6-8-2022
dtype: object

In [40]:
data["c"]

'6-8-2022'

In [42]:
data = ["sabtu","siang","6-8-2022"]
df_array = np.array([[" ","waktu"],["hari","sabtu"],["tanggal","6-8-2022"]])

In [43]:
data

['sabtu', 'siang', '6-8-2022']

In [44]:
df = pd.DataFrame(data = df_array)
df

0         1
0              waktu
1     hari     sabtu
2  tanggal  6-8-2022

In [45]:
data = np.array([["","Kolom1","Kolom2"],["Baris1",1,2],["Baris2",3,4]])

In [46]:
print(pd.DataFrame(data=data[1:,1:],index=data[1:,0],columns=data[0,1:]))

       Kolom1 Kolom2
Baris1      1      2
Baris2      3      4


In [47]:
df = pd.DataFrame(data=df_array[1:,1:],index=df_array[1:,0],columns=df_array[0,1:])
df

waktu
hari        sabtu
tanggal  6-8-2022

Membuat DataFrame dari 2D Array

In [64]:
import numpy as np

my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
print(my_2darray)

[[1 2 3]
 [4 5 6]]


In [65]:
df_array2 = pd.DataFrame(data=my_2darray,index=range(0,2),columns=[1,2,3])
print(df_array2)

   1  2  3
0  1  2  3
1  4  5  6


In [68]:
second_array = my_2darray[0:2,0:2]
second_array

array([[1, 2],
       [4, 5]])

In [69]:
df_2array = pd.DataFrame(data=second_array, index=range(0,2),columns=['A','B'])
df_2array

A  B
0  1  2
1  4  5

Series with Dictionary

In [3]:
import pandas as pd

my_series = pd.Series({"Jabar": "Bandung", "Jateng": "Semarang", "Jatim": "Surabaya", "Bali": "Denpasar"})
print(my_series)

Jabar      Bandung
Jateng    Semarang
Jatim     Surabaya
Bali      Denpasar
dtype: object


In [5]:
df_series = pd.DataFrame(data={'Provinsi': my_series.index, 'Ibukota': my_series.values})

print(df_series)

  Provinsi   Ibukota
0    Jabar   Bandung
1   Jateng  Semarang
2    Jatim  Surabaya
3     Bali  Denpasar


In [7]:
df_series = pd.DataFrame({'Provinsi': my_series.index, 'Ibukota': my_series.values})

print(df_series)

  Provinsi   Ibukota
0    Jabar   Bandung
1   Jateng  Semarang
2    Jatim  Surabaya
3     Bali  Denpasar


In [8]:
df = pd.DataFrame({"A": [1,2,3,4,5],"B": [6,7,8,9,10],"C": [11,12,13,14,15,]})
df.head()

A   B   C
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15

In [10]:
df_series2 = pd.DataFrame({
    "Provinsi": ["Jabar", "Jateng", "Jatim", "Bali"],
    "Ibu Kota": ["Bandung", "Semarang", "Surabaya", "Denpasar"]
})

print(df_series2)

  Provinsi  Ibu Kota
0    Jabar   Bandung
1   Jateng  Semarang
2    Jatim  Surabaya
3     Bali  Denpasar
