<a href="https://colab.research.google.com/github/mdanisw/bootcamp-training/blob/main/Intro_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

array_1 = np.array([1,2,3])
array_1

array([1, 2, 3])

In [ ]:
type(array_1)

numpy.ndarray

In [ ]:
list1 = [1,2,3]
type(list1)

list

In [ ]:
array_2 = np.array([[1,2,3],
                    [8,9,7],
                    [12,15,18]])
print(array_2)

[[ 1  2  3]
 [ 8  9  7]
 [12 15 18]]


In [ ]:
print(array_1)

[1 2 3]


In [ ]:
array_3 = np.array([[[1,2,3],[3,2,1],[9,9,9]],
                    [[9,10,11],[12,15,19],[1,2,3]]])

print(array_3)

[[[ 1  2  3]
  [ 3  2  1]
  [ 9  9  9]]

 [[ 9 10 11]
  [12 15 19]
  [ 1  2  3]]]


In [ ]:
array_1.shape

(3,)

In [ ]:
array_2.shape

(3, 3)

In [ ]:
array_3.shape

(2, 3, 3)

In [ ]:
zeros_1 = np.zeros(shape=(5,3,2,1))
print(zeros_1)

[[[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]]


In [ ]:
ones_1 = np.ones(shape=(5))
print(ones_1)

[1. 1. 1. 1. 1.]


In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(3.10)

array([0., 1., 2., 3.])

In [ ]:
np.arange(300,1000,100)

array([300, 400, 500, 600, 700, 800, 900])

In [ ]:
array_2

array([[ 1,  2,  3],
       [ 8,  9,  7],
       [12, 15, 18]])

In [ ]:
array_2 = array_2.reshape(-1)
array_2

array([ 1,  2,  3,  8,  9,  7, 12, 15, 18])

In [ ]:
array_2 = array_2.reshape(3,3)

In [ ]:
array_2 = np.array([[ 1,  2,  3],
       [ 8,  9,  7],
       [12, 15, 18],[1, 2, 8]])
array_2.shape

(4, 3)

In [ ]:
array_2 = array_2.reshape(3,4)

array_2

array([[ 1,  2,  3,  8],
       [ 9,  7, 12, 15],
       [18,  1,  2,  8]])

In [ ]:
array_2 = array_2.flatten()

In [ ]:
array_2

array([ 1,  2,  3,  8,  9,  7, 12, 15, 18,  1,  2,  8])

In [ ]:
array_2 = array_2.reshape(3,4)
array_2


array([[ 1,  2,  3,  8],
       [ 9,  7, 12, 15],
       [18,  1,  2,  8]])

In [ ]:
array_2 = array_2.transpose()
array_2

array([[ 1,  9, 18],
       [ 2,  7,  1],
       [ 3, 12,  2],
       [ 8, 15,  8]])

In [ ]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[10,20,30,40], [50,60,70,80]])

In [ ]:
arr_b = np.concatenate((arr1,arr2), axis=1)
arr_b

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

In [ ]:
arr_c = np.stack((arr1,arr2), axis=0)
arr_c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]]])

In [ ]:
arr_c = np.stack((arr1,arr2), axis=1)
arr_c

array([[[ 1,  2,  3,  4],
        [10, 20, 30, 40]],

       [[ 5,  6,  7,  8],
        [50, 60, 70, 80]]])

In [ ]:
arr = np.array([[1,2,3,4,9],[7,8,9,10,20],[12,13,14,15,16]])
arr

array([[ 1,  2,  3,  4,  9],
       [ 7,  8,  9, 10, 20],
       [12, 13, 14, 15, 16]])

In [ ]:
arr_s = np.array_split(arr,3)
arr_s

[array([[1, 2, 3, 4, 9]]),
 array([[ 7,  8,  9, 10, 20]]),
 array([[12, 13, 14, 15, 16]])]

In [ ]:
arr_s = np.array_split(arr.flatten(),2)
arr_s

[array([1, 2, 3, 4, 9, 7, 8, 9]), array([10, 20, 12, 13, 14, 15, 16])]

In [ ]:
arr

array([[ 1,  2,  3,  4,  9],
       [ 7,  8,  9, 10, 20],
       [12, 13, 14, 15, 16]])

In [ ]:
arr =np.resize(arr, (2,3))
arr

array([[1, 2, 3],
       [4, 9, 7]])

In [ ]:
arr =np.resize(arr, (2,4))
arr

array([[1, 2, 3, 4],
       [9, 7, 1, 2]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr = np.append(arr, [[10,11,12]],axis=0)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr = np.append(arr, [[10],[11]],axis=1)
arr

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr = np.insert(arr, 3, [10,22,33])
arr

array([ 1,  2,  3, 10, 22, 33,  4,  5,  6])

In [ ]:
arr = np.delete(arr,3)

In [ ]:
arr

array([ 1,  2,  3, 33,  4,  5,  6])

In [ ]:
arr[2]

3

In [ ]:
arr =np.array([1,1,1,1,1,4,4,4,46,6,6,6])
np.unique(arr)

array([ 1,  4,  6, 46])

In [ ]:
arr = np.array([[1,2,3,4,9],[7,8,9,10,20],[12,13,14,15,16]])
arr

array([[ 1,  2,  3,  4,  9],
       [ 7,  8,  9, 10, 20],
       [12, 13, 14, 15, 16]])

In [ ]:
arr[0:2,2:4]

array([[ 3,  4],
       [ 9, 10]])

In [ ]:
array_1 = np.array([1,2,3,4,5,6,7,8,9])
array_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array_1[1:3]

array([2, 3])

In [ ]:
array_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for x in array_1:
  print(x)

1
2
3
4
5
6
7
8
9


In [ ]:
txt = np.array(["apple", "melon", "banana", "mango", "durian","avocado"])
txt

array(['apple', 'melon', 'banana', 'mango', 'durian', 'avocado'],
      dtype='<U7')

In [ ]:
x = np.where(txt=="mango")
x

(array([3]),)

In [ ]:
a = np.array([1,2,10,99])
b = np.array([1,10,9,99])
a==b

array([ True, False, False,  True])

In [ ]:
c = a+b
c

array([  2,  12,  19, 198])

In [ ]:
c = a-b
c

array([ 0, -8,  1,  0])

In [ ]:
c = a*b
c

array([   1,   20,   90, 9801])